development:
  adapter: postgresql
  database: trellino_skeleton_development
  host: localhost
  pool: 5
  timeout: 5000

prodcution:
  adapter: postgresql
  database: trellino_prod
  host: localhost
  pool: 5
  timeout: 5000